# .NET Core
# Build and test projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Only trigger CI builds for the master branch, instead 
# of every branch. You'll automatically be configured to 
# build PRs, but you can't currently control that from the YAML directly
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

# We can run multiple jobs in parallel. For this project
# we are running Linux, Windows, and macOS jobs. For syntax details
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Provide a name for the job
- job: Linux

  # The VM image to use for the hosted agent. For a list of possible agents
  # see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
  # You can see the software installed on each agent at the same link.
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    buildConfiguration: 'Release'

  # The steps to run to execute the build.
  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: |
      mkdir $(Build.SourcesDirectory)\results
      dotnet test -f netcoreapp2.0 src/NaCl.Core.Tests --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      cp $(Build.SourcesDirectory)\NaCl.Core.Tests\coverage.cobertura.xml $(Build.SourcesDirectory)\results
      dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.4
    displayName: 'Unit testing'
    # Set environment variables for the build.
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    inputs:
      summaryFileLocation: $(Build.SourcesDirectory)\results\coverage.cobertura.xml
      reportDirectory: $(Build.SourcesDirectory)\results
      codecoverageTool: cobertura
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      projects: src/NaCl.Core/NaCl.Core.csproj
      publishWebProjects: false
      modifyOutputPath: true
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1

# Run a build on macOS at the same time
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: |
      mkdir $(Build.SourcesDirectory)\results
      dotnet test -f netcoreapp2.0 src/NaCl.Core.Tests --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      cp $(Build.SourcesDirectory)\NaCl.Core.Tests\coverage.cobertura.xml $(Build.SourcesDirectory)\results
      dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.4
    displayName: 'Unit testing'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    inputs:
      summaryFileLocation: $(Build.SourcesDirectory)\results\coverage.cobertura.xml
      reportDirectory: $(Build.SourcesDirectory)\results
      codecoverageTool: cobertura

# Run a build on Windows at the same time
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: VSTest@2
    displayName: 'Unit testing'
    inputs:
      codeCoverageEnabled: True
